### Exploratory analysis

#### In this notebook, I analyze the microdata for all live births in which the mother was **14 years old or younger** between 2004 and 2024.

#### The goal is to calculate the main descriptive statistics used throughout the project, including the number of births over time, rates per 1,000 live births, geographic distribution, and the demographic profile of the girls (such as age, race/color, and marital status).

In [1]:
import pandas as pd

df = pd.read_csv("microdados_sinasc_2004_2024.csv")
df.head()

/var/folders/qn/0_m8lc7j6hz111kp72r17lnh0000gn/T/ipykernel_40205/1948134314.py:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("microdados_sinasc_2004_2024.csv")

,ano,sigla_uf,sigla_uf_nome,id_municipio_nascimento,id_municipio_nascimento_nome,quantidade_filhos_vivos,quantidade_filhos_mortos,id_uf_mae,id_municipio_mae,id_municipio_mae_nome,idade_mae,escolaridade_mae,estado_civil_mae,ocupacao_mae,raca_cor_mae,idade_pai
0,2020,MT,Mato Grosso,5106174,Nova Nazaré,0.0,0.0,NaN,NaN,NaN,14,1 a 3 anos,União estável,NaN,Indígena,32.0
1,2020,MT,Mato Grosso,5103205,Colíder,0.0,0.0,51,5106422.0,Peixoto de Azevedo,14,8 a 11 anos,Solteira,999991.0,Indígena,NaN
2,2020,MT,Mato Grosso,5100359,Alto Boa Vista,0.0,0.0,51,5101852.0,Bom Jesus do Araguaia,12,4 a 7 anos,União estável,999992.0,Indígena,15.0
3,2020,MT,Mato Grosso,5103858,Gaúcha do Norte,0.0,0.0,51,5103858.0,Gaúcha do Norte,12,4 a 7 anos,Solteira,999992.0,Indígena,NaN
4,2020,MT,Mato Grosso,5107180,Ribeirão Cascalheira,0.0,0.0,51,5102702.0,Canarana,14,8 a 11 anos,União estável,999991.0,Indígena,22.0

In [732]:
df.shape

(493358, 16)

In [733]:
df.sort_values("ano", inplace=True)
df

,ano,sigla_uf,sigla_uf_nome,id_municipio_nascimento,id_municipio_nascimento_nome,quantidade_filhos_vivos,quantidade_filhos_mortos,id_uf_mae,id_municipio_mae,id_municipio_mae_nome,idade_mae,escolaridade_mae,estado_civil_mae,ocupacao_mae,raca_cor_mae,idade_pai
420076,2004,CE,Ceará,2312908,Sobral,0.0,0.0,NaN,NaN,NaN,12,4 a 7 anos,Solteira,800.0,NaN,NaN
374174,2004,PB,Paraíba,2507507,João Pessoa,0.0,0.0,NaN,NaN,NaN,14,4 a 7 anos,Solteira,800.0,NaN,NaN
374173,2004,PB,Paraíba,2507507,João Pessoa,0.0,0.0,NaN,NaN,NaN,14,4 a 7 anos,Solteira,600.0,NaN,NaN
374172,2004,PB,Paraíba,2507507,João Pessoa,0.0,0.0,NaN,NaN,NaN,14,1 a 3 anos,Solteira,800.0,NaN,NaN
374171,2004,PB,Paraíba,2507507,João Pessoa,0.0,0.0,NaN,NaN,NaN,13,4 a 7 anos,Solteira,600.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326178,2024,RS,Rio Grande do Sul,4301602,Bagé,0.0,0.0,43.0,4301602.0,Bagé,14,8 a 11 anos,Solteira,999991.0,Parda,23.0
326161,2024,RS,Rio Grande do Sul,4317202,Santa Rosa,0.0,0.0,43.0,4317202.0,Santa Rosa,14,8 a 11 anos,Solteira,999991.0,Branca,15.0
326099,2024,RS,Rio Grande do Sul,4304200,Candelária,0.0,0.0,43.0,4304200.0,Candelária,14,4 a 7 anos,Solteira,999991.0,Branca,NaN
326171,2024,RS,Rio Grande do Sul,4313508,Osório,0.0,0.0,43.0,4321600.0,Tramandaí,14,8 a 11 anos,Solteira,999992.0,Branca,17.0
493357,2024,SP,São Paulo,3520509,Indaiatuba,2.0,1.0,NaN,NaN,NaN,11,4 a 7 anos,Solteira,999992.0,NaN,NaN

### Number of cases per year (for the line chart)

In [821]:
cases_per_year = df.groupby("ano").size()
cases_per_year

ano
2004    26276
2005    26990
2006    27610
2007    27963
2008    28677
2009    27807
2010    27048
2011    27786
2012    28237
2013    27987
2014    28243
2015    26699
2016    24138
2017    22145
2018    21171
2019    19330
2020    17579
2021    17458
2022    14266
2023    13941
2024    12007
dtype: int64

### Number of cases per brazilian state

In [906]:
cases_per_state = (
    df.groupby("sigla_uf")
      .size()
      .reset_index(name="total_casos")
      .sort_values(by="total_casos", ascending=False)
)

cases_per_state

   sigla_uf  total_casos
25       SP        58046
4        BA        44692
13       PA        42762
9        MA        34430
18       RJ        31618
10       MG        28985
15       PE        27564
5        CE        26050
2        AM        25527
17       PR        21525
22       RS        16297
1        AL        14749
8        GO        13799
12       MT        11403
14       PB        11127
16       PI        10963
11       MS         9598
19       RN         9589
23       SC         9181
7        ES         7612
24       SE         7395
26       TO         6735
0        AC         5694
20       RO         5055
3        AP         4556
6        DF         4217
21       RR         4189

### Number of cases per city

In [907]:
cases_per_city = df.groupby("id_municipio_nascimento_nome").size()
cases_per_city.sort_values(ascending=False)

id_municipio_nascimento_nome
São Paulo           14221
Rio de Janeiro      12540
Manaus               9791
Recife               8188
Fortaleza            8036
                    ...
Moreilândia             1
Terra Alta              1
Coronel Ezequiel        1
Babaçulândia            1
Corumbataí              1
Length: 3549, dtype: int64

### Race of the mother in 2024

In [908]:
df["raca_cor_mae"].value_counts()

raca_cor_mae
Parda       198897
Branca       54568
Preta        14521
Indígena     11516
Amarela        738
Name: count, dtype: int64

In [1639]:
mother_race_24 = (
    df.loc[df["ano"] == 2024, "raca_cor_mae"]
      .value_counts()
)

mother_race_24

raca_cor_mae
Parda       8176
Branca      2028
Indígena     776
Preta        756
Amarela       35
Name: count, dtype: int64

In [1640]:
missing_race_24 = (
    df.loc[df["ano"] == 2024, "raca_cor_mae"]
      .isna()
      .value_counts()
)

missing_race_24

raca_cor_mae
False    11771
True       236
Name: count, dtype: int64

### Age of the mother

In [1641]:
mother_age = df.groupby("idade_mae").size()
mother_age.sort_values(ascending=False)

idade_mae
14    381812
13     94245
12     14388
11      2228
10       423
0        239
9         12
8         11
dtype: int64

In [1642]:
mother_age_24 = (
    df[df["ano"] == 2024]
      .groupby("idade_mae")
      .size()
      .sort_values(ascending=False)
)

mother_age_24

idade_mae
14    9183
13    2385
12     373
11      54
10       9
8        3
dtype: int64

### Marital status of the mother

In [1643]:
mother_marital_status = df.groupby("estado_civil_mae").size()
mother_marital_status.sort_values(ascending=False)

estado_civil_mae
Solteira                             410394
União estável                         63559
Casada                                10046
Ignorada                               5222
Separada judicialmente/divorciada       168
Viúva                                   120
dtype: int64

In [1644]:
mother_marital_status_24 = (
    df[df["ano"] == 2024]
      .groupby("estado_civil_mae")
      .size()
      .sort_values(ascending=False)
)

mother_marital_status_24

estado_civil_mae
Solteira                             10517
União estável                         1291
Ignorada                                79
Casada                                  71
Separada judicialmente/divorciada        1
dtype: int64

In [1645]:
missing_marital_status = (
    df.loc[df["ano"] == 2024, "estado_civil_mae"]
      .isna()
      .value_counts()
)

missing_marital_status

estado_civil_mae
False    11959
True        48
Name: count, dtype: int64

### Mother's education

In [1646]:
mother_education_24 = (
    df[df["ano"] == 2024]
      .groupby("escolaridade_mae")
      .size()
      .sort_values(ascending=False)
)

mother_education_24

escolaridade_mae
8 a 11 anos    5996
4 a 7 anos     5543
1 a 3 anos      234
Nenhuma         102
Ignorado         60
12 e mais        19
dtype: int64

In [1647]:
missing_education = (
    df.loc[df["ano"] == 2024, "escolaridade_mae"]
      .isna()
      .value_counts()
)

missing_education

escolaridade_mae
False    11954
True        53
Name: count, dtype: int64

### Number of living children

In [1648]:
mother_offspring_24 = (
    df[df["ano"] == 2024]
      .groupby("quantidade_filhos_vivos")
      .size()
      .sort_values(ascending=False)
)

mother_offspring_24

quantidade_filhos_vivos
0.0    11340
1.0      289
2.0       14
3.0        2
dtype: int64

### Father's age

In [1649]:
father_age_24 = (
    df[df["ano"] == 2024]
      .groupby("idade_pai")
      .size()
      .sort_values(ascending=False)
)

father_age_24

idade_pai
18.0    281
17.0    249
19.0    243
16.0    177
20.0    165
21.0    128
15.0    123
22.0    100
23.0     67
14.0     59
24.0     56
25.0     40
26.0     30
28.0     30
30.0     25
27.0     24
37.0     22
32.0     19
35.0     18
33.0     16
29.0     14
36.0     13
38.0     13
40.0     13
31.0     10
39.0     10
46.0     10
34.0      9
45.0      8
48.0      8
13.0      8
44.0      6
53.0      6
42.0      5
47.0      5
41.0      5
43.0      4
50.0      3
52.0      3
51.0      2
49.0      1
54.0      1
56.0      1
68.0      1
dtype: int64

In [1650]:
missing_father_age = (
    df.loc[df["ano"] == 2024, "idade_pai"]
      .isna()
      .value_counts()
)

missing_father_age

idade_pai
True     9976
False    2031
Name: count, dtype: int64

In [1651]:
missing_father_age = df.groupby("idade_pai").size()
missing_father_age.sort_values(ascending=False)
df["idade_pai"].isnull().sum()

np.int64(416488)

#### Load the dataset containing all live births to calculate the rate of births to girls aged 14 and younger per 1,000 live births.

In [1652]:
df_br = pd.read_csv("total_nascidos_municipio_2004_2024.csv")
df_br.head()

/Users/alexameirelles/.venvs/lede/lib/python3.13/site-packages/IPython/core/displayhook.py:292: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'

,ano,sigla_uf,id_municipio_nascimento,municipio_nascimento_nome,total_nascidos_vivos
0,2004,AC,1200013,Acrelândia,77
1,2004,AC,1200054,Assis Brasil,145
2,2004,AC,1200104,Brasiléia,780
3,2004,AC,1200138,Bujari,6
4,2004,AC,1200179,Capixaba,13

In [1653]:
df_br.columns

Index(['ano', 'sigla_uf', 'id_municipio_nascimento',
       'municipio_nascimento_nome', 'total_nascidos_vivos'],
      dtype='object')

In [1654]:
df_br.shape

(113516, 5)

In [1655]:
cases_per_year_br = (
    df_br.groupby("ano")["total_nascidos_vivos"]
         .sum()
)

cases_per_year_br

ano
2004    3026513
2005    3035033
2006    2944791
2007    2891077
2008    2934735
2009    2881461
2010    2861783
2011    2913019
2012    2905661
2013    2903853
2014    2979123
2015    3017489
2016    2857699
2017    2923436
2018    2944820
2019    2849063
2020    2730144
2021    2677097
2022    2560319
2023    2537573
2024    2389323
Name: total_nascidos_vivos, dtype: int64

### Rate per 1000 by year

In [1656]:
cases_per_state_total = (
    df_br.groupby("sigla_uf", as_index=False)["total_nascidos_vivos"]
      .sum()
)

In [1657]:
cases = (
    df.groupby("ano")
      .size()
      .rename("cases")
)
cases

ano
2004    26276
2005    26990
2006    27610
2007    27963
2008    28677
2009    27807
2010    27048
2011    27786
2012    28237
2013    27987
2014    28243
2015    26699
2016    24138
2017    22145
2018    21171
2019    19330
2020    17579
2021    17458
2022    14266
2023    13941
2024    12007
Name: cases, dtype: int64

In [1658]:
births = (
    live_births_by_state_year.groupby("ano")["total_nascidos_vivos"]
    .sum()
    .rename("live_births")
)

births

ano
2004    3026513
2005    3035033
2006    2944791
2007    2891077
2008    2934735
2009    2881461
2010    2861783
2011    2913019
2012    2905661
2013    2903853
2014    2979123
2015    3017489
2016    2857699
2017    2923436
2018    2944820
2019    2849063
2020    2730144
2021    2677097
2022    2560319
2023    2537573
2024    2389323
Name: live_births, dtype: int64

In [1659]:
rate = (
    pd.concat([cases, births], axis=1)
      .assign(rate_per_1000=lambda x: x["cases"] / x["live_births"] * 1000)
)

rate

      cases  live_births  rate_per_1000
ano
2004  26276      3026513       8.681939
2005  26990      3035033       8.892819
2006  27610      2944791       9.375878
2007  27963      2891077       9.672174
2008  28677      2934735       9.771581
2009  27807      2881461       9.650313
2010  27048      2861783       9.451450
2011  27786      2913019       9.538558
2012  28237      2905661       9.717926
2013  27987      2903853       9.637885
2014  28243      2979123       9.480307
2015  26699      3017489       8.848085
2016  24138      2857699       8.446656
2017  22145      2923436       7.574991
2018  21171      2944820       7.189234
2019  19330      2849063       6.784687
2020  17579      2730144       6.438855
2021  17458      2677097       6.521243
2022  14266      2560319       5.571962
2023  13941      2537573       5.493832
2024  12007      2389323       5.025273

### Rate per 1000 by state

In [1660]:
cases_by_state_year = (
    df.groupby(["sigla_uf", "ano"], as_index=False)
      .size()
      .rename(columns={"size": "total_cases"})
)
cases_by_state_year

    sigla_uf   ano  total_cases
0         AC  2004          263
1         AC  2005          249
2         AC  2006          274
3         AC  2007          270
4         AC  2008          268
..       ...   ...          ...
562       TO  2020          255
563       TO  2021          252
564       TO  2022          228
565       TO  2023          214
566       TO  2024          172

[567 rows x 3 columns]

In [1661]:
rate_by_state_year = (
    cases_by_state_year.merge(
        live_births_by_state_year,
        on=["sigla_uf", "ano"],
        how="left"
    )
)
rate_by_state_year

    sigla_uf   ano  total_cases  total_nascidos_vivos
0         AC  2004          263                 16871
1         AC  2005          249                 17831
2         AC  2006          274                 16446
3         AC  2007          270                 16182
4         AC  2008          268                 17994
..       ...   ...          ...                   ...
562       TO  2020          255                 23729
563       TO  2021          252                 23272
564       TO  2022          228                 22283
565       TO  2023          214                 23145
566       TO  2024          172                 21920

[567 rows x 4 columns]

In [1662]:
rate_by_state_year["cases_per_1000"] = (
    rate_by_state_year["total_cases"]
    / rate_by_state_year["total_nascidos_vivos"]
    * 1000
)

In [1663]:
rate_by_state_year

    sigla_uf   ano  total_cases  total_nascidos_vivos  cases_per_1000
0         AC  2004          263                 16871       15.588880
1         AC  2005          249                 17831       13.964444
2         AC  2006          274                 16446       16.660586
3         AC  2007          270                 16182       16.685206
4         AC  2008          268                 17994       14.893854
..       ...   ...          ...                   ...             ...
562       TO  2020          255                 23729       10.746344
563       TO  2021          252                 23272       10.828463
564       TO  2022          228                 22283       10.232015
565       TO  2023          214                 23145        9.246057
566       TO  2024          172                 21920        7.846715

[567 rows x 5 columns]

In [1664]:
rate_by_state_year.to_csv(
    "taxa_casos_por_mil_uf_ano.csv",
    index=False
)